services:
  webservice:
    build:
      context: ./webservice
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    mem_limit: 2048M
    environment:
      NODE_ENV: production
      PYTHON_SERVICE_URL: http://cgi-detector-service:8000/analyze
      PYTHON_SERVICE_URL_FEEDBACK: http://cgi-detector-service:8000/report
    depends_on:
      - cgi-detector-service
    networks:
      - cgi-detection-network

  cgi-detector-service:
    build:
      context: ./src/cgi-detector-service
      dockerfile: Dockerfile
    expose:
      - "8000"
    volumes:
      - cgi_forensics_data:/app/forensics_data
      - cgi_models_data:/app/forensics
    networks:
      - cgi-detection-network

volumes:
  cgi_forensics_data:
  cgi_models_data:

networks:
  cgi-detection-network:
    driver: bridge
